List<String> listPhrases = [];

const ListSports = [
  "ski",
  "football américain",
  "raquette",
  "velo",
  "badminton",
  "billard",
  "basketball",
  "bowling",
  "canoe-kayak",
  "escrime",
  "golf",
  "gymnastique",
  "fitness",
  "hockey",
  "judo",
  "karaté",
  "natation",
  "parkour",
  "rugby",
  "roller",
  "surf",
  "tennis",
  "tir à l'arc",
  "volley-ball",
  "patinage sur glace",
  "boxe",
  "athlétisme",
  "baseball",
  "football américain",
  "pétanque",
];

const listAnimals = [
  "chien",
  "chat",
  "pigeon",
  "crevette",
  "hiboux",
  "grenouille",
  "kangourou",
  "pingouin",
  "saumon",
  "cochon",
  "cheval",
  "renard",
  "hamster",
  "autruche",
  "lion",
  "dauphin",
  "sauterelle",
  "poulet",
  "mouton",
  "ours",
  "papillon",
  "requin",
  "lapin",
  "serpent",
  "elephant",
  "cerf",
  "hérisson",
  "canard",
  "chauve-souris",
  "pangolin",
];

//30
const listItems = [
  "parapluie",
  "casquette",
  "chapeau",
  "table",
  "escalier",
  "bouteille",
  "voiture",
  "raquette",
  "guitare",
  "piano",
  "balais",
  "ballon",
  "Eponge",
  "clé",
  "lunettes",
  "téléphone",
  "fourchette",
  "Banc",
  "valise",
  "helicoptère",
  "sable",
  "pluie",
  "monstre",
  "industrie",
  "entreprise",
  "soldat",
  "arme à feu",
  "billet",
  "mayonnaise",
  "goudron",
  "froid",
  "plume",
  "cigarette",
];

//30
const listCountries = [
  "France",
  "Belgique",
  "Corée du Sud",
  "Japon",
  "Chine",
  "USA",
  "Espagne",
  "Allemagne",
  "Danemark",
  "Pays Bas",
  "Pologne",
  "Royaume Uni",
  "Suède",
  "Norvège",
  "Grèce",
  "Russie",
  "Australie",
  "Canada",
  "Malaisie",
  "Indonésie",
  "Mexique",
  "Brésil",
  "Argentine",
  "Algérie",
  "Afrique du sud",
  "Inde",
  "Turquie",
  "Thaïlande",
  "Suisse",
  "Luxembourg",
];

//50
const listJobs = [
  "Astronaute",
  "Pilote d'avions",
  "Steward",
  "Barman",
  "Serveur (métier)",
  "Boucher",
  "Boulanger",
  "Cuisinier",
  "Agriculteur",
  "Chasseur",
  "Jardinier",
  "Coiffeur",
  "Acteur",
  "Auteur",
  "Clown",
  "Danseur",
  "Dessinateur",
  "Humoriste",
  "Musicien",
  "Architecte",
  "Plombier",
  "Fleuriste",
  "Opticien",
  "Médecin",
  "Avocat",
  "Juge",
  "Professeur",
  "Comptable",
  "Secrétaire",
  "Femme de ménage",
  "Youtubeur",
  "Ingénieur",
  "Développeur informatique",
  "Chanteur",
  "Traducteur",
  "Journaliste",
  "Photographe",
  "Président de la République",
  "Ministre",
  "Pharmacien",
  "Chauffeur",
  "Gendarme",
  "Détective",
  "Militaire",
  "Chimiste",
  "Psychologue",
  "Infirmier",
  "Pompier",
  "Vétérinaire",
];

//10
const listTransport = [
  "Voiture",
  "Vélo",
  "Moto",
  "Métro",
  "Bus",
  "Tramway",
  "Train",
  "Avion",
  "Bateau",
  "Hélicoptère",
  "Camion",
  "Fusée",
];

//10
const listColors = [
  "Rouge",
  "Bleu",
  "Jaune",
  "Vert",
  "Magenta",
  "Orange",
  "Violet",
  "Noir",
  "Blanc",
  "Marron",
  "Gris",
  "Beige",
  "Or",
  "Argent",
];

//30
const listFood = [
  "Couscous",
  "Nem",
  "Fajitas",
  "Salade",
  "Croissant",
  "Fromage",
  "Baguette de pain",
  "Paella",
  "Pizza",
  "Burger",
  "Pad Thaï",
  "Tacos",
  "Moule/frites",
  "Pâtes",
  "Sushi",
  "Curry",
  "Raclette",
  "Saucisson",
  "Crêpe bretonne",
  "Galette bretonne",
  "Hachis Parmentier",
  "Choucroute",
  "Bagel",
  "Bubble Tea",
  "Poutine (plat)",
  "Canard laqué",
  "Falafel",
  "Fish and chips",
  "Fruits de mer",
  "Glace",
  "Jus de fruit",
  "Milkshake",
  "Poké Bowl",
  "Soupe",
  "Tapas",
  "Wrap",
];

//30
const listMovies = [
  "Star wars",
  "Le seigneur des anneaux",
  "Indiana jones",
  "Avatar",
  "Titanic",
  "Jurassic Park",
  "Le roi lion",
  "Avengers",
  "La reine des neiges",
  "Fast and Furious",
  "Transformers",
  "Joker",
  "Toy Story",
  "Pokemon",
  "Harry Potter",
  "Intouchables",
  "Lucy",
  "Qu'est-ce qu'on a fait au bon dieu ?",
  "Bienvenue chez les Ch'tis",
  "La casa de papel",
  "L'attaque des titans",
  "Naruto",
  "One Piece",
  "The Walking Dead",
  "Games of Thrones",
  "Friends",
  "Stranger things",
  "Dix pourcent",
  "Matrix",
  "Retour vers le futur",
];

//50
const listStars = [
  "Angèle",
  "Marion Cotillard",
  "Emma Watson",
  "Natalie Portman",
  "Mimie Mathy",
  "Florence Foresti",
  "Alexandra Lamy",
  "Louane",
  "Valérie Lemercier",
  "Vanessa Paradis",
  "Nolwenn Leroy",
  "Claire Chazal",
  "Jenifer",
  "Dua Lipa",
  "Scarlett Johanson",
  "Rihanna",
  "Jennifer Lawrence",
  "Beyoncé",
  "Jennifer Anniston",
  "Kim Kardashian",
  "Kristen Stewart",
  "Louis de funès",
  "Gérard Depardieu",
  "Jean Dujardin",
  "Omar Sy",
  "François Cluzet",
  "Squeezie",
  "David Guetta",
  "Le bron james",
  "Fabrice Lucchini",
  "Goldman",
  "Soprano",
  "Gims",
  "Cyril Lignac",
  "Vianney",
  "Emmanuel Macron",
  "Jean Reno",
  "Dany Boon",
  "Thomas Pesquet",
  "Zinédine Zidane",
  "Stéphane Plaza",
  "Kylian Mbappe",
  "Stéphane Bern",
  "Julien Doré",
  "Michel Cymès",
  "Orelsan",
  "Trump",
  "Leonardo Di Caprio",
  "Bruce Lee",
  "Johnny Depp",
  "Tom Cruise",
];
